// Generated by Xata Codegen 0.28.3. Please do not edit.
import { buildClient } from "@xata.io/client";
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "filial_info",
    columns: [
      { name: "filial", type: "string" },
      { name: "cod_ibama", type: "int", notNull: true, defaultValue: "0" },
      { name: "transp", type: "string", notNull: true, defaultValue: "null" },
      { name: "dest", type: "string", notNull: true, defaultValue: "null" },
      {
        name: "tratamento",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
      { name: "und", type: "string", notNull: true, defaultValue: "null" },
      { name: "uf", type: "string", notNull: true, defaultValue: "null" },
      {
        name: "cnpj_filial",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
      {
        name: "cnpj_transp",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
      {
        name: "cnpj_dest",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
    ],
    revLinks: [{ column: "link_id", table: "mtr_info" }],
  },
  {
    name: "mtr_info",
    columns: [
      { name: "data", type: "datetime", notNull: true, defaultValue: "now" },
      { name: "volume", type: "float", notNull: true, defaultValue: "0" },
      { name: "userId", type: "string", notNull: true, defaultValue: "null" },
      { name: "link_id", type: "link", link: { table: "filial_info" } },
      { name: "n_mtr", type: "string", unique: true },
      { name: "n_cdf", type: "string", unique: true },
      { name: "n_nf", type: "string", unique: true },
      { name: "chave_nf", type: "string", unique: true },
    ],
  },
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
  databaseURL:
    "https://VICTOR-FAZEKAS-s-workspace-af4lll.us-west-2.xata.sh/db/PateoEsg",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
let instance = undefined;
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
